version: '2'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: es
    environment:
        - discovery.type=single-node
    ports:
      - 9200:9200
    
  auto_tagging:
    build: .
    depends_on:
      - es
    container_name: auto_tagging
    stdin_open: true
    tty: true


